# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Orbmu2k.nvidiaProfileInspector
PackageVersion: 2.4.0.16
PackageLocale: en-US
Publisher: Orbmu2k
PublisherUrl: https://github.com/Orbmu2k
PublisherSupportUrl: https://github.com/Orbmu2k/nvidiaProfileInspector/issues
Author: Orbmu2k
PackageName: NVIDIA Profile Inspector
PackageUrl: https://github.com/Orbmu2k/nvidiaProfileInspector
License: MIT License
LicenseUrl: https://github.com/Orbmu2k/nvidiaProfileInspector/blob/master/LICENSE
ShortDescription: This tool is used for modifying game profiles inside the internal driver database of the nvidia driver. All game profiles are provided by the nvidia driver, but you can add your own profiles for games missing in the driver database.
Description: This tool is used for modifying game profiles inside the internal driver database of the nvidia driver. All game profiles are provided by the nvidia driver, but you can add your own profiles for games missing in the driver database. You also have access to hidden and undocumented settings, which are not provided by the drivers control panel.
Moniker: NVIDIA Profile Inspector
ReleaseNotesUrl: https://github.com/Orbmu2k/nvidiaProfileInspector/releases/latest
Documentations:
- DocumentLabel: Step Modifications' Usage Guide
  DocumentUrl: https://stepmodifications.org/wiki/Guide:NVIDIA_Inspector
- DocumentLabel: PCGamingWiki's Usage Guide
  DocumentUrl: https://www.pcgamingwiki.com/wiki/Nvidia_Profile_Inspector
ManifestType: defaultLocale
ManifestVersion: 1.9.0
